name: Deploy

on:
  push:
    tags:
    - v*

jobs:
  deploy-build-windows:
    name: Deploy (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository
      run: |
        pip3 install setuptools
        pip3 install conan
        conan remote add conan-iceshard https://conan.iceshard.net/
        conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: Create package
      run: |
        conan create . fmt/7.0.3@iceshard/stable
    - name: Deploy
      run: |
        conan user iceshard -r conan-iceshard -p ${{ secrets.CONAN_PASSWORD }}
        conan upload -r conan-iceshard fmt/7.0.3@iceshard/stable --all

  deploy-build-ubuntu:
    name: Deploy (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan remote add conan-iceshard https://conan.iceshard.net/
        ~/.local/bin/conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        ~/.local/bin/conan profile new --detect default
        ~/.local/bin/conan profile update settings.compiler=clang default
        ~/.local/bin/conan profile update settings.compiler.version=9 default
        ~/.local/bin/conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Create package
      run: |
        ~/.local/bin/conan create . fmt/7.0.3@iceshard/stable
    - name: Deploy
      run: |
        ~/.local/bin/conan user iceshard -r conan-iceshard -p ${{ secrets.CONAN_PASSWORD }}
        ~/.local/bin/conan upload -r conan-iceshard fmt/7.0.3@iceshard/stable --all
